version: '3.7'

services:
    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        volumes:
            - ${PWD}/.docker/mysql:/var/lib/mysql
            - ${PWD}/.docker/_sql/:/docker-entrypoint-initdb.d/
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: golang
        networks:
            - web

    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
        volumes:
            - ${PWD}/.docker/mongodb:/data/db

networks:
    web:
        external: true
